version: '3.4'
services:
  currency_coverter:
    build:
      context: ./ConversionRateService
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
  sqs:
    image: roribio16/alpine-sqs
    ports:
      - '9324:9324'
  rest_api:
    build:
      context: ./RestAPI
      dockerfile: Dockerfile
    ports:
      - '3000:3000'